apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-chart-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: test-chart-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/app: test-chart-deployment
    spec:
      containers:
      - name: main
        image: bash:latest
        imagePullPolicy: IfNotPresent
        args:
        - "-c"
        - "sleep 100000"
